language: node_js
dist: trusty
sudo: required
node_js: 8
env:
  - PATH=$HOME/purescript:$PATH
install:
  - wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/v0.12.0/linux64.tar.gz
  - tar -xvf $HOME/purescript.tar.gz -C $HOME/
  - chmod a+x $HOME/purescript
  - npm install -g psc-package-bin-simple pulp
script:
  - psc-package install && pulp --psc-package build